ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\DepFileFactory.rb"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\DepFileFactory.rb"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\sourcedep-wiki.xml"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\sourcedep-wiki.xml"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\WikiDepFile.rb"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\WikiDepFile.rb"
ci -nc "C:/vreen00_toolset2/CxR_Toolset/Perf/toolset/cruise/checkout/script/tool/sourcedep"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\perf-export.xml"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\perf-export.xml"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\perf-paginas-s.txt"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\perf-paginas-s.txt"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\perf-paginas-wiki.txt"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\perf-paginas-wiki.txt"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\perf-paginas.txt"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\perf-paginas.txt"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\splitxml2files.tcl"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\splitxml2files.tcl"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\wiki-paginas.txt"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\wiki-paginas.txt"
ci -nc "C:/vreen00_toolset2/CxR_Toolset/Perf/toolset/cruise/checkout/script/tool/sourcedep/wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\CxR-Performance-raakvlakken.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\CxR-Performance-raakvlakken.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\CxR-Performance.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\CxR-Performance.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\HLD2008.1 Performance over de keten.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\HLD2008.1 Performance over de keten.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\JMeter-JMS-testen.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\JMeter-JMS-testen.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Performance tuning en capaciteitsmanagement.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Performance tuning en capaciteitsmanagement.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Performance-inrichten-omgeving.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Performance-inrichten-omgeving.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Performance-inrichting-BSB-test.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Performance-inrichting-BSB-test.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\PerformanceModellen.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\PerformanceModellen.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-JMeter.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-JMeter.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Documenten.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Documenten.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Grafieken.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Grafieken.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Guerrilla-Capacity-Planning.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Guerrilla-Capacity-Planning.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Keten.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Keten.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Logging.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Logging.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-logging2.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-logging2.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Opleidingsplan.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Opleidingsplan.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Release2.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Release2.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Release3.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Release3.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-termen.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-termen.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Tools.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-Tools.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-WASinstellingen.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-WASinstellingen.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-WCMOpmerkingen.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance-WCMOpmerkingen.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Performance.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceLQN.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceLQN.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceModelleren-Grafieken.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceModelleren-Grafieken.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceModelleren.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceModelleren.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceOpAn.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceOpAn.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformancePDQ.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformancePDQ.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformancePortalsCursus.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformancePortalsCursus.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceResultaten.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceResultaten.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTestCase.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTestCase.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTestCitrix.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTestCitrix.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTesten.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTesten.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTestMaken.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTestMaken.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTestOmgeving.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTestOmgeving.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTestSuite.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTestSuite.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTestUitvoeren.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceTestUitvoeren.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceToolset.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceToolset.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceToolsetInstalleren.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceToolsetInstalleren.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceToolsetWerking.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-PerformanceToolsetWerking.wiki"
ci -nc "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Schaalbaarheid.wiki"
ccadd "C:\vreen00_toolset2\CxR_Toolset\Perf\toolset\cruise\checkout\script\tool\sourcedep\wiki\pages\Portals-Schaalbaarheid.wiki"
ci -nc "C:/vreen00_toolset2/CxR_Toolset/Perf/toolset/cruise/checkout/script/tool/sourcedep/wiki/pages"
