#!/bin/bash

link=$1

if [[ -n "$link" ]]; then

    echo $link

else

	link="https://www.youtube.com/watch?v=mcixldqDIEQ"

    echo "no argument - demo url used :)"

fi

playfromurl='omxplayer -o local `youtube-dl -g  '$link'`'

#echo $playfromurl

eval $playfromurl


