#!/usr/bin/env tclsh

# wrap omxplayer, to log cmdline args for deleting symlinks after playing.

source [file join [file dirname [info script]] libwrap.tcl]

set DEBUG 0
# set LOGROOT "/home/pi/log"
# set LOGROOT .

# [2016-12-23 14:13] for now log only to one file.
set LOGNAMES {"ytplay.log"}

# TODO: now just log quite meaningless youtube url. Any way to find title?

proc main {argv} {
  logd "Calling ytplay-internal: $argv"
  set video [join $argv " "]
  set title [get_title $video]
  log "Start: $video (title: $title)"
  # cannot start in background using &, then omxremote will think it's finished.
  # also commands like pause are also given correctly now.
  exec -ignorestderr ytplay-internal {*}$argv
  log "Finished: $video (title: $title)"
  logd "exit wrapper, omxplayer should have finished playing"
}

# <title>David Nolen - The Functional Final Frontier - YouTube</title><l
proc get_title {video} {
  file delete yt.html
  exec -ignorestderr curl -o yt.html $video
  set text [read_file yt.html]
  if {[regexp {<title>([^<>]+)</title>} $text z title]} {
    return $title
  } else {
    return "not found"
  }
}

proc read_file {filename} {
  set f [open $filename r]
  set text [read $f]
  close $f
  return $text
}

main $argv

