./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/AllScripts/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CBF-BR/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CBF-CN/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CBF-DE/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CBF-FR/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CBF-IN/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CBF-JP/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CBF-KO/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CBF-NL/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CBF-RU/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CBF-UK/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CBF-US/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CorpLanding/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CQ5-CN-test/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CQ5-Mobile/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CQ5-S7-Video/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/CQ5-SupportFAQ/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/Mobile-landing/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/Mobile-US/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/MyPhilips/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/Shop/daily/daily.db
./dbscript.tcl -script daily-drop-pageitem.sql -db c:/projecten/Philips/Support-P4C/daily/daily.db
