{:config {:name :tutorial, :description "Tutorial recording", :order 0}
 :data
 [
  [:node-create [] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:value [:main :my-counter] nil 7]
  [:transform-enable [:main :my-counter] :inc [{:io.pedestal.app.messages/topic [:my-counter]}]]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 60.67]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 124]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 182]
  [:node-create [:main :other-counters] :map]
  [:node-create [:main :other-counters "abc"] :map]
  [:value [:main :other-counters "abc"] nil 124]
  [:node-create [:main :other-counters "xyz"] :map]
  [:value [:main :other-counters "xyz"] nil 51]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 315]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 237]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 227]
  :break
  [:value [:main :other-counters "abc"] 124 125]
  [:value [:main :average-count] 60.67 61]
  [:value [:main :max-count] 124 125]
  [:value [:main :total-count] 182 183]
  [:value [:pedestal :debug :dataflow-time] 237 221]
  :break
  [:value [:main :other-counters "abc"] 125 126]
  [:value [:main :average-count] 61 61.33]
  [:value [:main :max-count] 125 126]
  [:value [:main :total-count] 183 184]
  [:value [:pedestal :debug :dataflow-time] 221 254]
  :break
  [:value [:main :other-counters "xyz"] 51 52]
  [:value [:main :average-count] 61.33 61.67]
  [:value [:main :total-count] 184 185]
  [:value [:pedestal :debug :dataflow-time] 254 220]
  :break
  [:value [:main :other-counters "abc"] 126 127]
  [:value [:main :average-count] 61.67 62]
  [:value [:main :max-count] 126 127]
  [:value [:main :total-count] 185 186]
  [:value [:pedestal :debug :dataflow-time] 220 241]
  :break
  [:value [:main :my-counter] 7 8]
  [:value [:main :average-count] 62 62.33]
  [:value [:main :total-count] 186 187]
  [:value [:pedestal :debug :dataflow-time] 241 195]
  :break
  [:value [:main :my-counter] 8 9]
  [:value [:main :average-count] 62.33 62.67]
  [:value [:main :total-count] 187 188]
  [:value [:pedestal :debug :dataflow-time] 195 228]
  :break
  [:value [:main :my-counter] 9 10]
  [:value [:main :average-count] 62.67 63]
  [:value [:main :total-count] 188 189]
  [:value [:pedestal :debug :dataflow-time-avg] 227 226]
  [:value [:pedestal :debug :dataflow-time] 228 195]
  :break
  [:value [:main :my-counter] 10 11]
  [:value [:main :average-count] 63 63.33]
  [:value [:main :total-count] 189 190]
  [:value [:pedestal :debug :dataflow-time] 195 191]
  :break
  [:value [:main :my-counter] 11 12]
  [:value [:main :average-count] 63.33 63.67]
  [:value [:main :total-count] 190 191]
  [:value [:pedestal :debug :dataflow-time] 191 223]
  :break
  [:value [:main :my-counter] 12 13]
  [:value [:main :average-count] 63.67 64]
  [:value [:main :total-count] 191 192]
  [:value [:pedestal :debug :dataflow-time] 223 202]
  :break
  [:value [:main :my-counter] 13 14]
  [:value [:main :average-count] 64 64.33]
  [:value [:main :total-count] 192 193]
  [:value [:pedestal :debug :dataflow-time] 202 198]
 ]}