Ini = Section*

Section = Header Body?

Body = (KeyValue | <EmptyLine>)*

KeyValue = Key <Spaces '=' Spaces> Value <NewLine?>

Header = <'['> HeaderValue <']'> <NewLine>

<HeaderValue> = #'[^\r\n\[\]]+'

(* Key = #'[^\r\n=]+' *)
Key = WordNoEq (Spaces WordNoEq)*
Value = Epsilon | Word (Spaces Word)*

<Word> = #'[^\s]+'
<WordNoEq> = #'[^\s=]+'

(* Line/Value can be empty *)
<Line> = #'[^\r\n]*'
<EmptyLine> = NewLine

<NewLine> = #'\r?\n'

(* Spaces should not contain new lines *)
<Spaces> = Space*
<Space> = ' '

     
