Ini = Section*

Section = Header Body

Body = (KeyValue |
  <EmptyLine>)*

KeyValue = Key <Spaces '=' Spaces> Value <Spaces? NewLine?>

Header = <'['> HeaderValue <']'> <NewLine>

(* Header cannot contain brackets itself *)
<HeaderValue> = #'[^\r\n\[\]]+'

Key = Word-No-Eq (Spaces Word-No-Eq)*
Value = Epsilon | Word {Spaces Word}*

(* Value = Epsilon | Word (Spaces Word)* *)

<Word> = #'[^\s]+'
<Word-No-Eq> = #'[^\s=]+'

(* Line/Value can be empty *)
<Line> = #'[^\r\n]*'
<EmptyLine> = NewLine

<NewLine> = #'\r?\n'

(* Spaces should not contain new lines *)
<Spaces> = Space*
<Space> = ' '

     
